version: "3.8"

services:
  localstack:
      image: localstack/localstack:latest
      environment: 
        - AWS_DEFAULT_REGION=eu-west-2
        - EDGE_PORT=4566
        - SERVICES=sqs,dynamodb
      ports:
        - "4566:4566"
        - "4571:4571"
      volumes: 
        - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
